create database if not exists Salao_bp2;
use Salao_bp2;
#drop database salao_bp;
/* Em construção: */

CREATE TABLE CONTATO (
    cod_contato integer PRIMARY KEY,
    Descrição_cantato varchar(80),
    FK_TIPO_CONTATO_Codigo integer,
    FK_PESSOA_COD_PESSOA integer
);



CREATE TABLE TIPO_CONTATO (
    Codigo integer PRIMARY KEY,
    DESCRIÇÃO varchar(80)
);



CREATE TABLE PESSOA (
    CPF integer,
    SEXO char(1),
    COD_PESSOA integer PRIMARY KEY,
    NOME varchar(150),
    LOGIN_Email varchar(150),
    SENHA INT,
    FK_TIPO_USER_COD_TIPOUSER INT
);


CREATE TABLE TIPO_LOCAL (
    Cod_tipo_local INT PRIMARY KEY,
    Descrição varchar(80)
);


CREATE TABLE BAIRRO (
    Nome_bairro varchar(80),
    Cod_bairro INT PRIMARY KEY,
    FK_MUNICIPIO_Cod_Municipio INT
);




CREATE TABLE LOCAL (
    CEP INT,
    Descrição varchar(80),
    Numero_Casa INT,
    FK_PESSOA_COD_PESSOA integer,
    FK_TIPO_LOCAL_Cod_tipo_local INT,
    FK_BAIRRO_Cod_bairro INT
);



CREATE TABLE MUNICIPIO (
    Nome_municipio varchar(80),
    Cod_Municipio INT PRIMARY KEY,
    FK_ESTADO_Cod_Estado INT
);



CREATE TABLE ESTADO (
    Cod_Estado INT PRIMARY KEY,
    Nome_Estado CHAR(2)
);


CREATE TABLE ITENS (
    Cod_Item integer PRIMARY KEY,
    Nome varchar(150),
    Descrição varchar(80),
    Preço integer
);



CREATE TABLE Tipo_Status (
    Cod_Tipo_Status integer PRIMARY KEY,
    Descrição varchar(80)
);



CREATE TABLE AGENDA (
    Cod_Agenda INT PRIMARY KEY,
    Hora_Agenda time,
    Data_Agenda DATE,
    FK_SERVICO_FK_ITENS_Cod_Item integer,
    FK_PESSOA_COD_PESSOA integer,
    FK_Tipo_Status_Cod_Tipo_Status integer,
    FK_FUNCIONARIO_FK_PESSOA_COD_PESSOA_FUNC integer
);




CREATE TABLE SERVICO (
    TEMPO TIME,
    FK_ITENS_Cod_Item integer PRIMARY KEY
);




CREATE TABLE PRODUTO (
    VALIDADE DATE,
    FK_ITENS_Cod_Item integer PRIMARY KEY
);


CREATE TABLE TIPO_USER (
    COD_TIPOUSER INT PRIMARY KEY,
    DESCRIÇÃO varchar(150)
);


CREATE TABLE FUNCIONARIO (
    Salario FLOAT,
    FK_PESSOA_COD_PESSOA_FUNC integer PRIMARY KEY,
    FK_SERVICO_FK_ITENS_Cod_Item integer,
    FK_tipo_funcao_Codigo INT
);




CREATE TABLE Compra (
    COD_COMPRA INT PRIMARY KEY,
    DESCONTO FLOAT,
    DATA DATE,
    FK_PESSOA_COD_PESSOA integer
);



CREATE TABLE tipo_funcao (
    Codigo INT PRIMARY KEY,
    Descricao varchar(150)
);






CREATE TABLE Itens_compra (
    FK_Compra_COD_COMPRA INT,
    FK_ITENS_Cod_Item integer
);




 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_1
    FOREIGN KEY (FK_TIPO_CONTATO_Codigo)
    REFERENCES TIPO_CONTATO (Codigo);
 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_2
    FOREIGN KEY (FK_PESSOA_COD_PESSOA)
    REFERENCES PESSOA (COD_PESSOA);
 
ALTER TABLE PESSOA ADD CONSTRAINT FK_PESSOA_1
    FOREIGN KEY (FK_TIPO_USER_COD_TIPOUSER)
    REFERENCES TIPO_USER (COD_TIPOUSER);
 
ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_1
    FOREIGN KEY (FK_MUNICIPIO_Cod_Municipio)
    REFERENCES MUNICIPIO (Cod_Municipio);
 
ALTER TABLE LOCAL ADD CONSTRAINT FK_LOCAL_0
    FOREIGN KEY (FK_PESSOA_COD_PESSOA)
    REFERENCES PESSOA (COD_PESSOA);
 
ALTER TABLE LOCAL ADD CONSTRAINT FK_LOCAL_1
    FOREIGN KEY (FK_TIPO_LOCAL_Cod_tipo_local)
    REFERENCES TIPO_LOCAL (Cod_tipo_local);
 
ALTER TABLE LOCAL ADD CONSTRAINT FK_LOCAL_2
    FOREIGN KEY (FK_BAIRRO_Cod_bairro)
    REFERENCES BAIRRO (Cod_bairro);
 
ALTER TABLE MUNICIPIO ADD CONSTRAINT FK_MUNICIPIO_1
    FOREIGN KEY (FK_ESTADO_Cod_Estado)
    REFERENCES ESTADO (Cod_Estado);
 
ALTER TABLE AGENDA ADD CONSTRAINT FK_AGENDA_1
    FOREIGN KEY (FK_SERVICO_FK_ITENS_Cod_Item)
    REFERENCES SERVICO (FK_ITENS_Cod_Item);
 
ALTER TABLE AGENDA ADD CONSTRAINT FK_AGENDA_2
    FOREIGN KEY (FK_PESSOA_COD_PESSOA)
    REFERENCES PESSOA (COD_PESSOA);
 
ALTER TABLE AGENDA ADD CONSTRAINT FK_AGENDA_3
    FOREIGN KEY (FK_Tipo_Status_Cod_Tipo_Status)
    REFERENCES Tipo_Status (Cod_Tipo_Status);
 
ALTER TABLE AGENDA ADD CONSTRAINT FK_AGENDA_4
    FOREIGN KEY (FK_FUNCIONARIO_FK_PESSOA_COD_PESSOA_FUNC)
    REFERENCES FUNCIONARIO (FK_PESSOA_COD_PESSOA_FUNC);
 
ALTER TABLE SERVICO ADD CONSTRAINT FK_SERVICO_1
    FOREIGN KEY (FK_ITENS_Cod_Item)
    REFERENCES ITENS (Cod_Item);
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_1
    FOREIGN KEY (FK_ITENS_Cod_Item)
    REFERENCES ITENS (Cod_Item);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_1
    FOREIGN KEY (FK_PESSOA_COD_PESSOA_FUNC)
    REFERENCES PESSOA (COD_PESSOA);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_2
    FOREIGN KEY (FK_SERVICO_FK_ITENS_Cod_Item)
    REFERENCES SERVICO (FK_ITENS_Cod_Item);
 
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_FUNCIONARIO_3
    FOREIGN KEY (FK_tipo_funcao_Codigo)
    REFERENCES tipo_funcao (Codigo);
 
ALTER TABLE Compra ADD CONSTRAINT FK_Compra_1
    FOREIGN KEY (FK_PESSOA_COD_PESSOA)
    REFERENCES PESSOA (COD_PESSOA);
 
ALTER TABLE Itens_compra ADD CONSTRAINT FK_Itens_compra_0
    FOREIGN KEY (FK_Compra_COD_COMPRA)
    REFERENCES Compra (COD_COMPRA);
 
ALTER TABLE Itens_compra ADD CONSTRAINT FK_Itens_compra_1
    FOREIGN KEY (FK_ITENS_Cod_Item)
    REFERENCES ITENS (Cod_Item);